#point of this file -> service exposes your pods so other components can each them
apiVersion: apps/v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-app #service routes traffic to all pods that have this selector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
